function [label] = subfeaturize(inputcellarray,indexTarget,index_neg,indexD,negwords)
%SUBFEATURIZE generate feature label based on ith clinical notes
%   
    label = 0;
    if ~isempty(indexTarget) && ~isempty(index_neg)
        label = 0;    
        if (~isempty(strfind(inputcellarray,negwords{72}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{73}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{74}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{75}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{76}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{77}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{78}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{79}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{80}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{81}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{82}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{83}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{84}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{85}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{86}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{87}))) || ...
                    (~isempty(strfind(inputcellarray,negwords{88})))
                label = 0;
        elseif any(any(index_neg <= indexTarget.'))
            label = 0;
        elseif ~isempty(indexD)
            label = 0;
        else
            label = 1;
        end
    elseif ~isempty(indexTarget) && isempty(index_neg) && isempty(indexD)
        label = 1;
    else 
        label = 0;
    end
end

